### PR TITLE
[PR] Adding dynamic menu

### LINKED ISSUE #4: [EPIC] Feat: Dynamic Navigation Menu
To facilitate having an arbitrary number of [`lists`](https://github.com/dwyl/app/issues/271),
we need to **investigate** how to **_dynamically_ update** the **Navigation Menu** in a `Flutter` App. 

# Requirements / Roadmap:

+ [x] **`MUST`** allow `new` menu items to be added/removed by the `person`
+ [x] **`MUST NOT`** require re-compiling/re-releasing the `Flutter` App. 
+ [x] **`SHOULD`** allow the `person` to re-order the Nav Menu Items manually.
+ [x] **`SHOULD`** support `emoji`, `icons` or `images` (`GIF`, `JPEG`, `PNG` & `SVG` up to `64x64px`)
+ [x] **`SHOULD`** allow selection of `text color` 
+ [x] **`SHOULD`** allow for sub-menus up to 3 levels. e.g:
```
Menu Item                |  Level
________________________________
People.                      0
|__ Online Now               1
    |__ Family               2
    |__ Friends              2
        |__ Sports Team      3 
        |__ Gamerz           3
    |__ Work                 2
|__ Everyone                 1
```
+ [x] **`SHOULD`** be fully `i18n` compatible so can be translated seamlessly. see: https://github.com/dwyl/learn-flutter/issues/90

# Todo

The first thing we need to is:
+ [x] ***Investigate*** [and this should be time-boxed to **`T4h`**] if `Nav Menu` be dynamically generated 🔍 
e.g: based on `JSON` returned by a server response (and cached on the device). 
  + [x] Write-up your findings as comments in this issue and `if` you can get something working on `localhost`, 🧑‍💻 
  + [x] Create a `PR` extending this demo to include _dynamic_ menu items. 🚀 

> **Note**: my initial **`T5m`** Googling for "flutter navigation drawer dynamic" returned the following:
>  + https://nickyrabit.medium.com/navigation-drawer-with-dynamic-menu-and-submenu-using-flutters-pageview-457540beaff3
>  + https://github.com/nickyrabit/NavigationDrawer-with-Dynamic-Menu-and-Submenu-using-Flutter-Pageview
> So, thanks to @nickyrabit, it looks promising. 🤞

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #4 

This PR adds a menu that is dynamic, meaning it uses the information stemming from a `json` object to render the contents.
The `json` object consists of `MenuItems` (with an **id**, **title** and **tiles** - a list of `MenuItems` below).

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
I've managed to get the contents of `json` object to be rendered on the side menu drawer. Looking to `Future`-proof this and check how reorder could be implemented.

**Comment by nelsonic** [comment]
In principal we will use the same `position`-based ordering for the `drawer menu` 
so if you can get the drag-and-drop re-ordering working in `Flutter`-land that's awesome! 🤞

**Comment by LuchoTurtle** [comment]
Reordering should now work **locally**. Meaning it is not saving the changes to the `json` file. Reordering only works on the items on the same level, though.


https://user-images.githubusercontent.com/17494745/235232092-0439e627-ccc3-47e5-b918-8e0d94e036ea.mov

**Comment by LuchoTurtle** [comment]
I've managed to increase the code coverage to near 98%. Will tackle on getting it to 100%. 

I've successfully tested dragging and dropping. Flutter's [`longPress`](https://api.flutter.dev/flutter/flutter_test/WidgetController/longPress.html) doesn't work, so I had to create a custom function  using [`startGesture`](https://api.flutter.dev/flutter/flutter_test/TestGesture-class.html) to simulate drag an drop on widget tests.

image

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for persisting. Testing is mega important to us. 🙏

**Comment by LuchoTurtle** [comment]
I've added tests and the complete step-by-step tutorial on how to implement navigation menu. I'm not going to mark this as completed because I want to go over the rest of the requirements, namely setting the color of the text by `JSON`

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for the update. Thank you for continuing on this quest. 🚀

**Comment by LuchoTurtle** [comment]
I think I got a basic `i18n` working. The user inputs the `title` field with possible locales and the system works accordingly. However, some tests are failing, even though fundamentally I didn't make breaking changes. It's probably because of how the widgets are initialized on the tests. 💭

**Comment by LuchoTurtle** [comment]
Fixed a few bugs regarding reordering and fixed the decoration border that was overlapping on nested elements. Added both of these to the README.
Also fixed the CI to use the latest version of Flutter. By using [`collection`](https://pub.dev/packages/collection), `flutter_test` was having conflicts with the `collection` package, so I had to force it to use the latest.

Not yet marking this for review because I want to add a simple navigation to a page displaying the menu item information. After that, everything should be thoroughly documented and ready for submission.

**Comment by LuchoTurtle** [comment]
This should be done for review. Added navigation, tests to cover the full app and added a CI to fix typos on a separate PR. Because the changes added are substantial, there's a chance I got a typo here and there.

**Comment by nelsonic** [comment]
@LuchoTurtle could you please record a short video/GIF of the final result. 🎥 
@SimonLab if you have time please do an initial pass at reviewing this. 🙏

**Comment by LuchoTurtle** [comment]
https://github.com/dwyl/flutter-navigation-menu-demo/assets/17494745/bdf17e4b-d1c8-4609-88a3-9572a9476f57

Here's an overview:
- working `i18n`.
- navigation on static menu items.
- navigation on dynamic menu items.
- showing support for `icon`, `emoji` and `images` that are formatted to `64x64px`.
- customization of dynamic menu text colour.
- persistable reordering of dynamic menu items.

**Comment by LuchoTurtle** [comment]
Could this PR be merged? I believe it's complete and easily mergeable 🆗

**Review by nelsonic — APPROVED** [review]
Yeah, I reviewed it at the time. 👀 
Had asked @SimonLab to have a look, but I think he's focussed on other priority items. 👌 
Merging. ✅

**Pull request merged**
